const FETCH_REQUEST_WEATHER = 'weather/FETCH_REQUEST_WEATHER';
const FETCH_SUCCESS_WEATHER = 'weather/FETCH_SUCCESS_WEATHER';
const FETCH_ERROR_WEATHER = 'weather/FETCH_ERROR_WEATHER';

const FETCH_REQUEST_FORECAST = 'forecast/FETCH_REQUEST_FORECAST';
const FETCH_SUCCESS_FORECAST = 'forecast/FETCH_SUCCESS_FORECAST';
const FETCH_ERROR_FORECAST = 'forecast/FETCH_ERROR_FORECAST';

export default {
  FETCH_REQUEST_WEATHER,
  FETCH_SUCCESS_WEATHER,
  FETCH_ERROR_WEATHER,
  FETCH_REQUEST_FORECAST,
  FETCH_SUCCESS_FORECAST,
  FETCH_ERROR_FORECAST
};