const FETCH_REQUEST_WEATHER = 'weather/FETCH_REQUEST_WEATHER';
const FETCH_SUCCESS_WEATHER = 'weather/FETCH_SUCCESS_WEATHER';
const FETCH_ERROR_WEATHER = 'weather/FETCH_ERROR_WEATHER';

export default {
  FETCH_REQUEST_WEATHER,
  FETCH_SUCCESS_WEATHER,
  FETCH_ERROR_WEATHER,
};
